Gizra/gizra.com

- app/_scss/main.scss
- app/_scss/pages/_blog.scss
- app/blog/index.html
- app/index.html
#171 
Blog margins:
Fax in footer:
> Fix blog margins & Add fax to footer.

- app/_scss/main.scss
> Remove wrong definition of li tag

- app/index.html
@RachelBaram something like this?
> Add link to about story from homepage

- .travis.yml
- Gruntfile.js
> Fix travis.

- app/_includes/footer.html
- app/_scss/_footer.scss
> Update US office address.

- app/_scss/pages/_about-page.scss
#262 
Just change the font type and color of the text.
@amitaibu what do you think ?
Original font:
softer version:
> About us story page

- .travis.yml
#301
This is a temp fix, until we get Visual regression back on.
> Fix travis by removing webdriverCSS

- app/_layouts/default.html
- app/js/js-live-monitor.js
#296 
@amitaibu Works fine with `grunt serve` and with `grunt serve:dist`.
> Add JS Live monitor.

- app/_includes/title.html
- app/_layouts/default.html
- app/_scss/pages/_service-page.scss
- app/blog/index.html
- app/team/index.html
> Duplicated titles

- app/_posts/2016-01-24-entity-relations-graph.md
> Fix the link markdown.

- app/_scss/pages/_service-page.scss
- app/services/hr/index.html
> Add Staffing & Recruitment Industry service page

- app/_includes/footer.html
- app/_scss/_footer.scss
#331
Fix USA address and adding the Facebook icon.
@kazabooboo
@RachelBaram
> Add facebook icon and fix usa address details

- app/_includes/clients.html
> Fix: Broken link under our work.

- app/_includes/post_teaser.html
> Remove symbol from the post teaser.

- app/_includes/footer.html
> Added title to social links

- app/_includes/team-members.html
> Fix and add alt to the images.

- app/_scss/pages/_about-page.scss
> About page: Narrowed the paragraphs on wide screens

- app/_includes/footer.html
- app/_scss/main.scss
> Fix office usa office address

- app/contact/drupalcon2016-nola/index.html
- app/contact/drupalcon2016/index.html
> Add contact us page for Drupalcon

- app/contact/drupalcon2016-nola/index.html
- app/contact/thank-you/index.html
> Add a thank you page and redirect

- app/_includes/footer.html
> Change NY address

- app/_includes/header.html
- app/_layouts/case.html
- app/_layouts/post.html
- app/_scss/_general.scss
- app/_scss/_header.scss
- app/_scss/_homepage.scss
- app/_scss/pages/_blog-page.scss
- app/_scss/pages/_contact-page.scss
- app/blog/index.html
- app/contact/index.html
- app/jobs/experienced-web-dev/index.html
#415 
As opposed to aligning header to new margins, give header some balance to lessen the visual disruption
**Homepage**
**Blog landing**
**Blog post**
> Balance headers by right justifying menu

- app/_includes/team-members.html
- app/_scss/pages/_team-page.scss
- app/team/index.html
@RachelBaram does this work better for you?
> Changes to team page layout #2

- app/services/elm/index.html
- app/services/hr/index.html
Fixes headers on pages linked from the services page, deploy with #425
> Fix headers on service pages

- app/_layouts/post.html
- app/_scss/_general.scss
- app/_scss/pages/_post-page.scss
- behat/features/bootstrap/FeatureContext.php
Alternative to #346 with wide format.
Discussed with @RachelBaram and I think we agree this is better.
> Wide format blog post

- app/_layouts/post.html
#436 
I can't see disqus on my machine (so no screenshot), but this should do it.
> Fix comments on blog post.

- app/_layouts/case.html
- app/_scss/pages/_case-page.scss
- app/case-studies/ibli/index.md
- app/case-studies/openscholar/index.md
> Case study page based on blog page.

- app/_scss/_general.scss
- app/_scss/pages/_post-page.scss
#448 
Moved this to _post-page.scss because this is the only place it occurs.
> Fix demo block links

- app/_scss/_about.scss
- app/_scss/_footer.scss
- app/_scss/_header.scss
- app/_scss/_homepage.scss
- app/_scss/_mixins.scss
- app/_scss/pages/_case-page.scss
- app/_scss/pages/_post-page.scss
- app/_scss/pages/_services-page.scss
- app/services/index.html
> Change default link behavior

- app/_includes/about.html
#459 @RachelBaram Here's a start.
> Update Gizra Way text

- app/_includes/footer.html
> Change US Office phone number and zip code.

- app/_includes/projects.html
not sure how this slipped through, and for that long...
> Fix intro text for projects

- app/_layouts/default.html
- app/js/main.js
- bower.json
#456 
@RachelBaram This can have positive SEO impact (supposedly)
> Add AnchorJS for deep link anchors

- app/_layouts/default.html
- app/_posts/2016-09-15-email-template-in-drupal.md
This fixes a typo in the metatag PR on the metatag image type.
> Hotfix metatag

- app/_layouts/default.html
> Change og:image label to property for facebook

- _config.yml
> Name and title changes

- app/_scss/_homepage.scss
- app/index.html
#486 & #470
This just adds 2 more posts and sets the height of that section to 1000px on every desktop-width.
This is a little hard to demo on a 13'' Macbook, so maybe @guytepper or @DavidKohav  , you want to pull it local?
> Set two rows of blog teasers on home page and make height static

- app/_posts/2016-07-28-elm-with-electron.md
Change the title of the post, as suggested by @RachelBaram  in #471
> Blog post: Elm & Electron.

- _config.yml
> Set to false employees who are not working any more.

- app/_includes/footer.html
> Update U.S. Address

- app/taxonomy/term/1/all/feed/index.html
> Added property to the guid

- src/assets/javascript/Main.js
- team_app/src/Attribute/Model.elm
- team_app/src/GizraTeam.elm
> Rename tag to Pescetarian

- src/_story/what-matters/index.html
> Fix grammer issues found by @nqthqn

- src/_includes/project.html
- src/_layouts/case_study.html
- src/_layouts/default.html
- src/_layouts/post.html
- src/_layouts/story.html
- src/assets/scss/style.scss
Some minor layout and typography.
> Proposed Typography/Layout

- src/assets/javascript/Main.js
- team_app/src/GizraTeam.elm
> Fix Ryan's github link

- README.md
- src/_posts/2017-03-02-cto-shadow-david.md
> Title case for last post + README Addition

- src/_includes/disqus.html
> Disqus - HTTPS

- src/jobs/project-manager/index.html
> Add PM job page

- README.md
- src/_posts/2017-06-01-nuntius-bot-introduction.md
> Fix Nuntius embedded images.

- src/assets/javascript/Main.js
- team_app/src/GizraTeam.elm
> Update team page (09/12/2017).

- src/_posts/2017-05-18-transcript-why-drupal.md
PR for #603 
@IshaDakota could you review this?
> Fixes embedded images of David's post

- src/_posts/2018-03-07-podcast-episode-2.md
> Podcast episode 2

- src/_layouts/default.html
> Remove maximum scale designation

- src/_layouts/default.html
> Add language tag to the HTML element
